# Section for configuring the bots
Bots:

  # Movement duration in bot ticks (10 ticks per second, smaller values make the bot move faster)
  # Default: 10
  MovementDuration: 10

  # Rotation duration in ticks (10 ticks per second, smaller values make the bot rotate faster)
  # Default: 10
  RotationDuration: 10

  # Allow bots to break blocks
  # Default: true
  AllowBlockBreaking: true

  # Allow bots to use certain group of scripts
  # LOCAL - only scripts that belong to the bot
  # SHARED - only global scripts that are available to all bots
  # ALL - both local and shared scripts
  # Default: ALL
  AllowedScripts: "ALL"

  # Format for the bot's chat messages
  # Default: "&7[Bot] {message}"
  ChatFormat: "&7[Bot] {message}"

  # The maximum number of entries in bot's memory
  # This is not bot's working memory, but memory used to store data that persists through bot restarts
  MaxMemoryEntries: 32

# Section for configuring rules for the programming language used by bots
Scripts:

  # The maximum number of concurrent function calls
  # Each function call takes some RAM, so this limit is used to prevent bots from using too much memory
  # Normally, the default limit is enough for most cases
  # Default: 8
  MaxFunctionCallStackSize: 8

  # The maximum number of variables that can be used in a script
  # Default: 20
  MaxVariablesCount: 20

  # The maximum number of function definitions that can be defined in a script
  MaxFunctionsCount: 10