<program> ::= ((<define_var> | <define_func> | <call_function> | <object_function_call> | <if_statement> | <for_loop>) <new_line>?) <program>*

<define_var> ::= "var" <spaces> <name> (<var_assign>?)
<var_assign> ::= <spaces> "=" <spaces> <number>

<define_func> ::= "function" <spaces> <name> "(" <parameters> ")" <spaces> "{" <function_block> "}"
<parameters> ::= <name> | <name> "," <spaces> <parameters>
<function_block> ::= <new_line>? <spaces>? ((<define_var> | <call_function> | <if_statement> | <for_loop>) <new_line>?) <spaces>? <function_block>* <spaces>?

<spaces> ::= " "*
<name> ::= ([a-z] | [A-Z])+
<number> ::= [0-9]+
<new_line> ::= "\n"*

<call_function> ::= <name> "(" <call_args>? ")"
<call_args> ::= <number> | <number> "," <spaces> <call_args>

<object_function_call> ::= <name> ("." <call_function>)+

<b_exp> ::= "i < 5"
<exp> ::= "i++"

<if_statement> ::= "if" <spaces> "(" <number> ")" <spaces> "{" <function_block> "}"
<for_loop> ::= "for (" <define_var> ";" <b_exp> ";" <exp> "){" <function_block> "}"