name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "feature-request", "api", "change"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.3.1
        - 0.3.0
        - 0.2.0
        - 0.1.2
        - 0.1.1
        - 0.1.0
      default: 0
    validations:
      required: true
  - type: textarea
    id: server_version
    attributes:
      label: Server version
      description: What is your server version?
      placeholder: Paper 1.20.1
    validations:
      required: true
